name: Generate README

on:
  push

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
      shell: sh

    - name: Run Python Script
      run: |
        cd scripts && python readme-generator.py
      shell: sh

    - name: Check for Changes
      id: check_changes
      run: |
        git diff --exit-code || echo "Changes detected"
      continue-on-error: true

    - name: Add README
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m 'Update README.md via GitHub Actions'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.check_changes.outcome == 'success'
