name: Run Python Script on Merge

on:
  push

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Run Python Script
      run: |
        python ${{github.workspace}}/scripts/readme_generator.py
      shell: sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
